# Generated by Django 4.2.5 on 2023-11-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='emigration',
            field=models.IntegerField(default=0),
        ),
    ]
