# Generated by Django 4.2.5 on 2023-11-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_country_emigration'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rok', models.IntegerField()),
                ('liczba_osob', models.IntegerField()),
            ],
        ),
    ]
