# Generated by Django 4.2.5 on 2023-11-16 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_othermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emigration',
            fields=[
                ('id_emigration', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('number_of_emigrants', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='OtherModel',
        ),
        migrations.RemoveField(
            model_name='country',
            name='emigration',
        ),
        migrations.AddField(
            model_name='country',
            name='area',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='continent',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='flag_path',
            field=models.CharField(default='ścieżka_do_domyślnej_flagi', max_length=255),
        ),
        migrations.AddField(
            model_name='country',
            name='phone_code',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='population',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='country',
            name='capital',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='country',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='emigration',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.country'),
        ),
    ]
